language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      cache: apt
      dist: xenial

    - os: osx
      compiler: clang

env:
  global:
    - BUILD_NAME="Ubertooth-$TRAVIS_OS_NAME-`date --iso-8601`-$TRAVIS_COMMIT"
    - ARTEFACT_BASE=$TRAVIS_BUILD_DIR/artefacts/
    - ARTEFACT_PATH=$ARTEFACT_BASE/$BUILD_NAME

addons:
  apt:
    packages:
      - libbluetooth-dev
      - libusb-1.0-0-dev
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - libstdc++-arm-none-eabi-newlib

  homebrew:
    taps: PX4/homebrew-px4
    packages:
       - gcc-arm-none-eabi

before_script:
  - wget https://github.com/greatscottgadgets/libbtbb/archive/master.zip -O libbtbb-master.zip
  - unzip libbtbb-master.zip
  - mkdir libbtbb-master/build
  - cd libbtbb-master/build
  - cmake ..
  - make
  - sudo make install
  - export CFLAGS="-g -Wall -Wextra -Werror -Wno-zero-length-array"

script:
  # Host code
  - mkdir $TRAVIS_BUILD_DIR/host/build
  - cd $TRAVIS_BUILD_DIR/host/build
  - cmake ..
  - make
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi
  # Firmware
  - cd $TRAVIS_BUILD_DIR/firmware
  - make

deploy:
  provider: pages
  verbose: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: greatscottgadgets/nightly-builds
  local-dir: $ARTEFACT_BASE
  on:
    branch: master
